# Generated by Django 4.0.2 on 2022-04-29 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=250, verbose_name='Наименование заказчика')),
                ('buyer_city', models.CharField(max_length=250, verbose_name='Город заказа')),
                ('buyer_phone', models.IntegerField(verbose_name='Номер телефона')),
                ('buyer_FIO', models.CharField(max_length=300, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Worforce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workforce_surname', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('workforce_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('workforce_patronymic', models.CharField(max_length=250, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Каммерсант',
                'verbose_name_plural': 'Коммерсанты',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateField(verbose_name='Дата бронирования')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan.buyer', verbose_name='Заказчик')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan.product', verbose_name='Породкция')),
                ('workforce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan.worforce', verbose_name='Коммерсант')),
            ],
            options={
                'verbose_name': 'Резерв',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='reserve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.reserve', verbose_name='Резерв'),
        ),
    ]
