# Generated by Django 4.0.2 on 2022-04-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_buyer_worforce_reserve_plan_reserve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserve',
            options={'verbose_name': 'Резерв', 'verbose_name_plural': 'Резерв'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.CharField(max_length=50, verbose_name='Номер продукта'),
        ),
    ]
