# Generated by Django 4.0.2 on 2022-07-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_plan_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='model',
        ),
    ]
