# Generated by Django 4.0.2 on 2022-07-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.product', verbose_name='Продукт'),
        ),
    ]
