# Generated by Django 4.0.2 on 2022-07-06 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_alter_plan_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.product', verbose_name='Продукт'),
        ),
    ]
