# Generated by Django 4.0.2 on 2022-08-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_remove_plan_date_plan_date_guild_plan_date_merchant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='plan',
        ),
    ]
