# Generated by Django 4.0.2 on 2022-08-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_act_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='plan',
        ),
        migrations.AddField(
            model_name='plan',
            name='act',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.act', verbose_name='Акт'),
        ),
    ]
