# Generated by Django 4.0.2 on 2022-08-04 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_alter_plan_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.act', verbose_name='Акт'),
        ),
    ]
