# Generated by Django 4.0.2 on 2022-08-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_alter_plan_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_expense_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expense', models.DateField(auto_now=True, verbose_name='Срок списания')),
                ('id_expense_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.product', verbose_name='Связанная продукция')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Продукция', to='plan.product', verbose_name='Связанная продукция')),
            ],
            options={
                'verbose_name': 'Привязка продукции',
                'verbose_name_plural': 'Привязка продукции',
            },
        ),
    ]
