# Generated by Django 4.0.2 on 2022-08-12 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_remove_product_expense_product_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_expense_product',
            name='id_expense_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.product', verbose_name='Связанная продукция'),
        ),
        migrations.AlterField(
            model_name='product_expense_product',
            name='product_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Продукция', to='plan.product', verbose_name='Продукция'),
        ),
    ]
