# Generated by Django 4.0.2 on 2022-08-24 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0021_plot_alter_product_guild'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plot',
            options={'verbose_name': 'Участок', 'verbose_name_plural': 'Участок'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='foreman',
        ),
        migrations.AddField(
            model_name='product',
            name='foreman',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Бригадир'),
            preserve_default=False,
        ),
    ]
