# Generated by Django 4.0.2 on 2022-08-24 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0022_alter_plot_options_remove_plan_foreman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='foreman',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guild',
        ),
        migrations.AddField(
            model_name='plan',
            name='foreman',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Бригадир'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='guild',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='plan.plot', verbose_name='Участок'),
            preserve_default=False,
        ),
    ]
